const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Tween,
		C3.Behaviors.LOS,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Mikal_3DObject,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.mikal_rotate_shape,
		C3.Plugins.skymen_set_fov,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.skymen_set_fov.Acts.SetFOV,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.mikal_rotate_shape.Acts.SetRotationAngles,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.AngleWithin,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Exps.anglediff,
		C3.Behaviors.Bullet.Exps.AngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Building01: 0},
	{"3DCamera": 0},
	{"8Direction": 0},
	{Player: 0},
	{Mouse: 0},
	{Skybox: 0},
	{ZombieBillboard: 0},
	{Keyboard: 0},
	{Building02: 0},
	{Building03: 0},
	{Wall02: 0},
	{TrashBottom: 0},
	{Fence: 0},
	{Building04: 0},
	{Building05: 0},
	{VanBottom: 0},
	{Wall03: 0},
	{Wall01: 0},
	{Wall04: 0},
	{TrashTop: 0},
	{InitialX: 0},
	{InitialY: 0},
	{InitialAngle: 0},
	{Tween: 0},
	{GunOverlay: 0},
	{Ground: 0},
	{InvisibleWall01: 0},
	{InvisibleWall02: 0},
	{LineOfSight: 0},
	{ZombieCollision: 0},
	{Sprite: 0},
	{Pipe01: 0},
	{Pipe02: 0},
	{AC: 0},
	{ElectricPanelBox: 0},
	{Crate: 0},
	{ZombieAnimations: 0},
	{Building5: 0},
	{VanTop: 0},
	{VanWindow: 0},
	{Cables01: 0},
	{Cables2: 0},
	{Tutorial: 0},
	{audio: 0},
	{Chanuka: 0},
	{Particles: 0},
	{"1nazwiska": 0},
	{"3DShapeWall": 0},
	{sciabnaRP: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{speed: 0},
	{Sprite3: 0},
	{Audio: 0},
	{TiledBackground3: 0},
	{"3DObject": 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{Imie: 0},
	{LastDistance: 0},
	{IsMovingTowardPlayer: 0},
	{AngleToPlayer: 0},
	{MovementAngle: 0},
	{MonologCooldown: 0},
	{Bullet: 0},
	{NPCPolityk: 0},
	{"3DShapeSchody": 0},
	{Sprite4: 0},
	{hp: 0},
	{Rotate: 0},
	{Sine: 0},
	{"3DShapeKartonTrzaskowski": 0},
	{Opcja: 0},
	{Konwersacje: 0},
	{PS: 0},
	{pobrane: 0},
	{result: 0},
	{range: 0},
	{PlayerCam: 0},
	{result2: 0},
	{Fade: 0},
	{smoke3_: 0},
	{Rotate3D: 0},
	{Coin: 0},
	{NPCfacePolityk: 0},
	{"3DUstawy": 0},
	{pakt: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{scianaKuluaryq: 0},
	{TiledBackground8: 0},
	{plaskorzezba: 0},
	{sufitKuluary: 0},
	{rotatey: 0},
	{rotatex: 0},
	{rotatez: 0},
	{Sprite5: 0},
	{Sprite2: 0},
	{"3DShapePotykacz": 0},
	{Plakat: 0},
	{Trigger: 0},
	{TriggerCamera: 0},
	{SCAM: 0},
	{NPCwoman: 0},
	{cooldown: 0},
	{Typ: 0},
	{Klub: 0},
	{diff: 0},
	{manNPC: 0},
	{NPCfaceMan: 0},
	{NPCfaceWoman: 0},
	{PS2: 0},
	{Sprite6: 0},
	{cameraman: 0},
	{SLOT: 0},
	{hand: 0},
	{krzyz: 0},
	{Informacja: 0},
	{TiledBackground9: 0},
	{drzwiPhotoroom: 0},
	{sciana: 0},
	{TiledBackground10: 0},
	{"3DShape3": 0},
	{TiledBackground11: 0},
	{Flaga: 0},
	{items: 0},
	{TiledBackground12: 0},
	{PlakatLGBT: 0},
	{Variable1: 0},
	{Cinematic: 0},
	{TiledBackground13: 0},
	{"3DShapeBufet": 0},
	{"3DShape2": 0},
	{oldmatPrzodCzerwony: 0},
	{"3DShape": 0},
	{Results: 0},
	{TiledBackground14: 0},
	{TiledBackground15: 0},
	{quest: 0},
	{genowefa: 0},
	{menu: 0},
	{transparent: 0},
	{open: 0},
	{Drzwi1: 0},
	{Sprite7: 0},
	{"3DShapeSAFE": 0},
	{number: 0},
	{Code: 0},
	{"3DShapeFridge": 0},
	{"3DShapekRZESLO": 0},
	{textureUID: 0},
	{villager: 0},
	{SetFOV: 0},
	{FlagaUE: 0},
	{FlagaUEnaziemi: 0},
	{fire: 0},
	{Billboards: 0},
	{Family1: 0},
	{PunktyS: 0},
	{konwersacja: 0},
	{w1: 0},
	{w2: 0},
	{w3: 0},
	{w4: 0},
	{PunktyZ: 0},
	{PunktyU: 0},
	{chanuki: 0},
	{camera: 0},
	{CameraAngle: 0},
	{FOV: 0},
	{InputLeft: 0},
	{InputRight: 0},
	{InputUp: 0},
	{InputDown: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{AxisAngle: 0},
	{weapon: 0},
	{WALKSPEED: 0},
	{RUNSPEED: 0},
	{Controls: 0},
	{KOD: 0},
	{isLeft: 0},
	{angleToPlayer: 0}
];

self.InstanceType = {
	Building01: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Skybox: class extends self.I3DShapeInstance {},
	ZombieBillboard: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	Building02: class extends self.I3DShapeInstance {},
	Building03: class extends self.I3DShapeInstance {},
	Wall02: class extends self.I3DShapeInstance {},
	TrashBottom: class extends self.I3DShapeInstance {},
	Fence: class extends self.I3DShapeInstance {},
	Building04: class extends self.I3DShapeInstance {},
	Building05: class extends self.I3DShapeInstance {},
	VanBottom: class extends self.I3DShapeInstance {},
	Wall03: class extends self.I3DShapeInstance {},
	Wall01: class extends self.I3DShapeInstance {},
	Wall04: class extends self.I3DShapeInstance {},
	TrashTop: class extends self.I3DShapeInstance {},
	GunOverlay: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	InvisibleWall01: class extends self.ISpriteInstance {},
	InvisibleWall02: class extends self.ISpriteInstance {},
	ZombieCollision: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Pipe01: class extends self.I3DShapeInstance {},
	Pipe02: class extends self.I3DShapeInstance {},
	AC: class extends self.I3DShapeInstance {},
	ElectricPanelBox: class extends self.I3DShapeInstance {},
	Crate: class extends self.I3DShapeInstance {},
	ZombieAnimations: class extends self.ISpriteInstance {},
	Building5: class extends self.I3DShapeInstance {},
	VanTop: class extends self.I3DShapeInstance {},
	VanWindow: class extends self.I3DShapeInstance {},
	Cables01: class extends self.I3DShapeInstance {},
	Cables2: class extends self.I3DShapeInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	Chanuka: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	_1nazwiska: class extends self.ITiledBackgroundInstance {},
	_3DShapeWall: class extends self.I3DShapeInstance {},
	sciabnaRP: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	_3DObject: class extends self.IWorldInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	NPCPolityk: class extends self.ISpriteInstance {},
	_3DShapeSchody: class extends self.I3DShapeInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	_3DShapeKartonTrzaskowski: class extends self.I3DShapeInstance {},
	Konwersacje: class extends self.ISpriteFontInstance {},
	PS: class extends self.ITextInstance {},
	pobrane: class extends self.ISpriteInstance {},
	result: class extends self.ISpriteInstance {},
	range: class extends self.ISpriteInstance {},
	PlayerCam: class extends self.ISpriteInstance {},
	result2: class extends self.ISpriteInstance {},
	smoke3_: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	NPCfacePolityk: class extends self.ISpriteInstance {},
	_3DUstawy: class extends self.I3DShapeInstance {},
	pakt: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	scianaKuluaryq: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	plaskorzezba: class extends self.ISpriteInstance {},
	sufitKuluary: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	_3DShapePotykacz: class extends self.I3DShapeInstance {},
	Plakat: class extends self.ISpriteInstance {},
	Trigger: class extends self.ISpriteInstance {},
	TriggerCamera: class extends self.ISpriteInstance {},
	SCAM: class extends self.ISpriteInstance {},
	NPCwoman: class extends self.ISpriteInstance {},
	manNPC: class extends self.ISpriteInstance {},
	NPCfaceMan: class extends self.ISpriteInstance {},
	NPCfaceWoman: class extends self.ISpriteInstance {},
	PS2: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	cameraman: class extends self.ISpriteInstance {},
	SLOT: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	krzyz: class extends self.ISpriteInstance {},
	Informacja: class extends self.ITextInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	drzwiPhotoroom: class extends self.ISpriteInstance {},
	sciana: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	_3DShape3: class extends self.I3DShapeInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Flaga: class extends self.ISpriteInstance {},
	items: class extends self.ISpriteInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	PlakatLGBT: class extends self.ISpriteInstance {},
	Cinematic: class extends self.ISpriteInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	_3DShapeBufet: class extends self.I3DShapeInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	oldmatPrzodCzerwony: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Results: class extends self.ISpriteInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	genowefa: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	transparent: class extends self.ISpriteInstance {},
	Drzwi1: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	_3DShapeSAFE: class extends self.I3DShapeInstance {},
	Code: class extends self.ISpriteInstance {},
	_3DShapeFridge: class extends self.I3DShapeInstance {},
	_3DShapekRZESLO: class extends self.I3DShapeInstance {},
	villager: class extends self.ISpriteInstance {},
	SetFOV: class extends self.IInstance {},
	FlagaUE: class extends self.ISpriteInstance {},
	FlagaUEnaziemi: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	Billboards: class extends self.I3DShapeInstance {},
	Family1: class extends self.ISpriteInstance {}
}